# Generated by Django 4.1.1 on 2022-09-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='prise',
            new_name='price',
        ),
    ]
