# Generated by Django 4.1.1 on 2022-09-11 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0002_rename_news_article_rename_prise_article_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='article',
            name='price',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news_feed.author'),
        ),
    ]
