# Generated by Django 4.1.1 on 2022-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0003_author_rename_name_article_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
